# .pre-commit-config.yaml
repos:
  # Python code formatter
  - repo: https://github.com/psf/black
    rev: '25.11.0'
    hooks:
      - id: black
        language_version: python3.12

  # Python import sorter
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        language_version: python3.12

  # Django HTML templates formatter
  # - repo: https://github.com/rtts/djhtml
  #   rev: '3.0.10'
  #   hooks:
  #     - id: djhtml
  #     - id: djcss
  #     - id: djjs

